# Copyright 2021 Suresoft Technologies Inc.
# Licensed under the MIT

FROM ubuntu:18.04
WORKDIR workspace
RUN apt update
RUN apt install -y git python pkg-config autogen automake libtool

RUN git config --global user.email "minhyuk@suresofttech.com"
RUN git config --global user.name "Peter Kwon"
