name: Deploy Wiki

on:
  push:
    branches: [main]

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Set up environment
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Make Wiki Files
        run: |
          PYTHONPATH=defects4cpp/ python wiki_generator.py
      - name: Push Wiki Changes
        uses: Andrew-Chen-Wang/github-wiki-action@v3
        env:
          WIKI_DIR: wiki/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: ${{ secrets.WIKI_AUTHOR_EMAIL }}
          GH_NAME: ${{ github.repository_owner }}
