name: docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: docker-practice/actions-setup-docker@master
      - name: Set up Python 3.8
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
          pip install -r docs/requirements.txt
          pip install pytest-html pytest-cov genbadge[all]

      - name: Generate test report
        run: |
          PYTHONPATH=bugscpp/ python -m pytest --basetemp=mydir --junitxml=./reports/junit/junit.xml --html=./reports/junit/report.html --ignore tests/taxonomy
          sudo rm -rf mydir

      - name: Generate coverage
        run: |
          # Output format is default value of genbadge. See docs of genbadge for more information.
          PYTHONPATH=bugscpp/ python -m pytest --basetemp=mydir --cov-report=xml:reports/coverage/coverage.xml --cov-report=html:reports/coverage --cov=bugscpp --ignore tests/taxonomy

      - name: Generate docs
        run: |
          mv bugscpp/bugscpp.py bugscpp/bugscpp.py
          make --directory=docs api
          make --directory=docs taxonomy
          make --directory=docs html

      - name: Generate badges
        run: |
          genbadge tests --output-file ./reports/junit/tests-badge.svg
          genbadge coverage --output-file ./reports/coverage/coverage-badge.svg
          # Remove .ignore not to be comitted.
          rm -f reports/coverage/.gitignore
          mv reports docs/build/html/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
